/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chronica.ui.logistics;

import chronica.model.business.Task.TaskDirectory;
import chronica.model.business.User.User;
import chronica.model.business.User.UserDirectory;
import chronica.model.business.event.EventDirectory;
import chronica.model.business.role.RoleDirectory;
import chronica.ui.customer.CustomerPanel;
import chronica.ui.nav.NavBar;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author arvindranganathraghuraman
 */
public class LogisticsMainPage extends javax.swing.JPanel {
    JPanel PanelContainer;
    User logistics;
    RoleDirectory roleDirectory;
    UserDirectory userDirectory;
    TaskDirectory taskDirectory = new TaskDirectory();
    EventDirectory eventDirectory;

    /**
     * Creates new form LogisticsMainPage
     */
    public LogisticsMainPage(JPanel PanelContainer, User authUser, RoleDirectory roleDirectory, UserDirectory userDirectory, EventDirectory eventDirectory) {
        initComponents();
        this.PanelContainer = PanelContainer;
        this.logistics = authUser;
        this.roleDirectory = roleDirectory;
        this.userDirectory = userDirectory;
        this.eventDirectory = eventDirectory;
        render();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        navBar = new javax.swing.JPanel();
        LogisticsPanel = new javax.swing.JPanel();

        navBar.setLayout(new java.awt.CardLayout());
        jSplitPane1.setLeftComponent(navBar);

        LogisticsPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(LogisticsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LogisticsPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel navBar;
    // End of variables declaration//GEN-END:variables
private void render() {
        NavBar panel = new NavBar(PanelContainer, navBar, logistics, roleDirectory, userDirectory,eventDirectory);
        navBar.add("NavBar", panel);
        CardLayout layout = (CardLayout) PanelContainer.getLayout();
        layout.next(PanelContainer);

        LogisticsPanel panel1 = new LogisticsPanel(LogisticsPanel, logistics, roleDirectory, taskDirectory, eventDirectory);
        LogisticsPanel.add("LogisticsPanel", panel1);
        
        layout.next(PanelContainer);

    }
}
